version: "3.9"

services:

  master:
    depends_on:
      - master_db
      - slave
    build: .
    ports:
      - "9000:8080"
    environment:
      MODE: master
      SLAVE_ADDR: http://slave:8080
      DATABASE_ADDR: postgresql://master_db/postgres?user=postgres&sslmode=disable

  master_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  slave:
    depends_on:
      - slave_db
    build: .
    ports:
      - "8000:8080"
    environment:
      MODE: slave
      DATABASE_ADDR: postgresql://slave_db/postgres?user=postgres&sslmode=disable

  slave_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
